---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin-password: AgAIOme4+OCcII55NA5Vqi1sJT/nh4awpSO8Mo1upe8debWHH5/eFrBMBOxT+UEaEhA31wk/ZZsnvWwaYL1wNOm7zMW9JSRJanQzuWmMnHfMqB/zuerhl7H6ugQqK22gEHhiQ7Fh76L2elT4SQB3PKhC3180CVmyx2xKHsUeWyWBJg4B4PwEeFvq1vxrNgOhNDT7l5m4GI6kMjhagLlOkKb7bOYzpCqAiF5G8EYyw6iUM+YYzMUnsTXp9HYZpbj61aHwipgVle9EJO7JsoQ7nNxvDb8IlyjZX2KonumZH/TUm94Bi8cX3sj/ESyOSfu+bAj0oNDN4O8rFWtzaSqwWpNO4rgnBzCwdNGr6UxmCL9RwVeo27y4jmtrRmXTPP1WGbAlkTZUg5mlvYL3v/Yr2MDtQLDDu6FI6wQzd8ppWn8UUqLFbWF/KDvfQ4R3qxcrp79Rc6MKpPGhbTV3fBhGkF1xVw3BEoqGqqvv8WYHeOyfhyxXg3tN0ok2eXJN31jylOTqv7Ov8WgQY1nz310ckwYm9lrl4tFpEtFZ/MK/ZxgyOsq4vRw1+2jg8tb691P747j1cs2LPYCa7qK7wCE8M1bmB6zUZyEP5ifRHhkJQXyzapQ73WBDkF0bFIQV2Qi+ytLIojh7RdI9rC72z9U+MWC1IF8musavTq+Jcyalm6AHmJAVE3YmGOYgGuurILVbi3McVF+v20Duue1sFj0aQoAYB+oyFIS44yk00rgXF0gR4OtP05aL5T4O
    admin-user: AgAJA5kNa9UTc7vx2Ahf537x2sMxYV4zcWSv+nTNW3xzsfwzm40rHuLvhi3xQY65gpHMt8MDj47ji/GDFIBA5hxZHf7cPIDaMjg3fwMzTHB2GXhoHZRffL/0Frrgzte6oyjmEZ8BunzxvR2XEEYzsZeKFaFrYT4pOpdfRw7Jz2L6xe7fcALoq0AayPVQ5nuReNi9ctdTTc0Ry4HbIpEgAexRs7Ef+pCLvAWWG3hr5IJNwQhJSiv0s/RLZ/M5S/dXPN+MsS7uT2SCCpVYNGAw1QG3IHWit8aZeXCRd2LRPw28m7w04LhKF4FtEVAxgqnLBBJntlTyRqhNQybwY6kY+QOxHbHeKtnNIVb3BQZySQcerjCumTPOtl1d11Hh36a1cFrK9qq+li2yTt03s0IHCPs+SMzs9kREyTy+tFqcqhvRIpoHMtWJ6ms8liSTyeOCLAJuj0vbMRTA66AeoIVTpFJdRc7vCtR8qwH81lb8IcdKvsKVUZ6W/ZxDXRCHq5SNoODhEV2cyc9wSt8HAwq61tr2kleqc/1VTlYoZFncAwQKdH1FQiTVUWkdgWpWHkwp4zhZlal3OE0i+VnCyRGzTOD4Z3lHnPerKIICBEs9C0w3GsrBk4x6OCkzpnkj87yGBMhi4NwZiwzk7U6s65eNgoIpM4wzCEYazFmEZM4iVKwIlDsJFFVxpH1YPlgSnq2vs2yraxpaJA==
  template:
    metadata:
      name: grafana-admin
      namespace: default
