apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }} 
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        securityContext:
          privileged: true
        readinessProbe:
          tcpSocket:
            port: 8123
        livenessProbe:
          tcpSocket:
            port: 8123
        startupProbe:
          tcpSocket:
            port: 8123
        resources:
          requests:
            memory: 128M
          limits:
            memory: 768M
        volumeMounts:
        - name: homeassistant
          mountPath: /config
        {{- if .Values.device }}
        - name: conbee
          mountPath: {{ .Values.device }}
        {{- end }}
      volumes:
      - name: homeassistant
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-{{ .Release.Namespace }}
      {{- if .Values.device }}
      - name: conbee
        hostPath:
          path: {{ .Values.device }}
      {{- end }} 
