apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          securityContext:
            privileged: true
          env:
            - name: TZ
              value: {{ .Values.timezone | default  "Europe/Berlin" }}
          readinessProbe:
            tcpSocket:
              port: 8123
          livenessProbe:
            tcpSocket:
              port: 8123
          startupProbe:
            initialDelaySeconds: 60
            tcpSocket:
              port: 8123
          resources:
            requests:
              memory: 512M
            limits:
              memory: 1024M
          volumeMounts:
            - name: homeassistant
              mountPath: /config
            - name: dbus
              mountPath: /run/dbus
              readOnly: true
      volumes:
        - name: homeassistant
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}
        - name: dbus
          hostPath:
            path: /run/dbus
