apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}
spec:
  storageClassName: ""
  volumeName: home-assistant
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
