apiVersion: v2
name: postgresql
type: application
version: 1.0.123
# renovate: image=bitnamicharts/postgresql
appVersion: "18.11.2"
dependencies:
  - name: postgresql
    version: "18.11.2"
    repository: oci://registry-1.docker.io/bitnamicharts
