apiVersion: v2
name: postgresql
type: application
version: 1.0.129
# renovate: image=bitnamicharts/postgresql
appVersion: "18.11.3"
dependencies:
  - name: postgresql
    version: "18.11.4"
    repository: oci://registry-1.docker.io/bitnamicharts
