nfs:
  server: 192.168.1.5
  path: /nfs/postgresql

postgresql:
  auth:
    username: homeassistant
    database: homeassistant
    existingSecret: postgresql-credentials
    secretKeys:
      adminPasswordKey: postgres-password
      userPasswordKey: password
  primary:
    service:
      type: LoadBalancer
      annotations:
        metallb.io/loadBalancerIPs: 192.168.1.26
    persistence:
      existingClaim: "postgresql"
    metrics:
      enabled: true
    startupProbe:
      enabled: true
      initialDelaySeconds: 60
      periodSeconds: 15
      failureThreshold: 60
      timeoutSeconds: 10
    livenessProbe:
      initialDelaySeconds: 60
      periodSeconds: 30
      failureThreshold: 10
      timeoutSeconds: 10
    readinessProbe:
      initialDelaySeconds: 30
      periodSeconds: 15
      failureThreshold: 10
      timeoutSeconds: 10
  volumePermissions:
    enabled: true
