apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
data:
  mosquitto.conf: |
    listener 1883
    listener 8083
    protocol websockets
    allow_anonymous true
    log_timestamp true
    log_timestamp_format %Y-%m-%d %H:%M:%S
