apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}
spec:
  storageClassName: ""
  volumeName: mosquitto
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
