apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: victoria-metrics 
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: victoria-metrics-volume-snapshot
spec:
  volumeSnapshotClassName: volume-snapshot-class
  source:
    persistentVolumeClaimName: victoria-metrics
