apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: default
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/resource-policy: keep
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: cert-manager
    repoURL: https://github.com/0Bu/rpi-k3s-cluster.git
    targetRevision: HEAD
  syncPolicy: {}
