apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meross-thermostat-bot
  namespace: default
  annotations:
    helm.sh/resource-policy: keep
    meross-thermostat-bot/source-sha: 9178ed20b8c64262c92503c5526227c945d1ce28
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: ghcr.io/0bu/charts
    chart: meross-thermostat-bot
    targetRevision: 0.3.0-sha9178ed20b8c64262c92503c5526227c945d1ce28
    helm:
      releaseName: meross-thermostat-bot
      valuesObject:
        image:
          repository: ghcr.io/0bu/meross-thermostat-bot
          tag: 9178ed20b8c64262c92503c5526227c945d1ce28
          pullPolicy: IfNotPresent
        imagePullSecrets:
          - name: ghcr-registry
        meross:
          hosts:
            - 192.168.107.114
            - 192.168.107.125
            - 192.168.107.172
          mdns:
            enabled: true
            hostNetwork: true
        mqtt:
          brokerURL: tcp://mosquitto:1883
        secret:
          name: meross-thermostat-bot-device-key
          key: MEROSS_DEVICE_KEY
        sealedSecret:
          create: true
          encryptedDeviceKey: "AgBB+ZLqr2gfNC6y93HrtTT7qKH/CxPl33Bkv8I0ZgZRD8/BtuMeQLEhkhINWeStkAXRJpRhDljA8SKOIb3ktLVFn5dAENz/4pmFpH+dqBe9W3XwVtC6wJnoEIj4Sf7tHwSY3FvQHbrpc2swtxCQTszUOPpfr2k7qQ6u6g3EN02OiL5nChqAy6CnEIYlwK3dKJeGi8dBsQeIgdp7OTrRKeq5vAAh0qLYf+Yx4TQQNA3LhrLWAbRPaPkMrxdpjZVU2UPo2WTy5tbB7ILovfCTwrMMTnP1SqDtr5AlnDNsE4ocWBpl9QQtEcb32cqswhefmP+vD4ytPA8rYK9T5Xbu1FZLUJXSBfWxwK7Ch84wGxabpqKqKv2ZsfGFmnr8Xhwsi8XKZHIyUDulhCE1FKQxHfhX/7uIqGfE3PEQ23z73uVmFylxR0TzxcNVjpsXpsZWBtlaxqOhTEzbCG6B2VPoTEavFN7rmm+DJElS7FojouESs5Q3nQ1PA3F0yY5F+OPh484FhswcfJdqPeDAJQaQ9UUMeQdVuRW7ZrUgc93Kqq3iOygOqbywFkHB5+9Grj1ScxzKRKBLzvge5R+iBocoO4pOURUX21oyTauW0mICKkMaLFO9KJ61spZZk7KIjg40T7PNqZyIT+HpbsB9b5RYGCf7SX4nqDhasBuZev1n2n2EjHmixyRSXpkFHPjnq/+4topzOv8krB+fW1iCf7TDMC7ast8RFvitfI9rnfUc3CcCFQ=="
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-registry
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgCRsfbJkhd+vN5lSIhAV88hdv0TDLOAnf6gClUL1jbURcT6YwGntm2U1ca8FZjYhusPczm3e/1sz5dwOMljBPJ0Hxvu/D1rG/D1zqp1DlMrxJK5TB1A5EIY1Qp7d+F3zABIU9CNGjwL7ZL/0BRvDWnHVXnMqeK9CWjxHeg5u8FloNq461v7fWhIEVQxEFNmiZQNvGLmkeMvFhGSDA4J/Klo8xDUFkXVif4TZP4UYXoihSb7GGIsqoHXZh+dIk1F+Lke/mK0wG3iHQ+h92+Ol0nufeL9auBT2dKNNXSsBH47MmhIFIzuKM8RNduw0vqpnoTZsjCOcvj2AJGXUngf8MHZdLyxYO9XLE4ggLThVdChl3WqRjvGh2gLwXqrpOWYh+lcaiVyDGxb9/kgKTjo8pmeq+EZZmAAnljX1wTKZwNGByxINkxmn4c3Qt2Bj4IJX+zqRXVGX1SdcRnZU1jblZlxJGvYtuwJrG2DJvCCZ7gVZktexVCWwZJUBQMh8c7910INxnagbZVwrege3cODHKY2hoqghyQs8AW9GmFyv3JJyw5GG2L8fPSOxQbu1Y7lnJe7l15zNn49fZfaXCJ0EfKgkkpjbxafXXB+CnMY01yRDBcV1zmh/PKdJK1eDWVtllkMLbIzrz6dKTwaKMfkTOcLlaLQLc9pz2Np9+7EsjG0hzdALgF+WCzsXK21rDaz8td8JyuF95TWP71vmxyWeMneuFS/MvX7/nDZHXZD+q6/mcFfDReSiWzjZ8eQTdnBxdkEL8DU143wxPlYBMlng8sKq/zSC/0EljJRCgSq1HqjgqS300XrCnBzigRnyrJR04rZoAPbZ2mosEgvVnqDdUN0mwJ7vBaroo6rtt7Kqt29D8UrmXzbbuX6kLQPOY6nb4JGj63XbPQ3YtDpty7SoFDZVGm3/g==
  template:
    metadata:
      name: ghcr-registry
      namespace: default
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: repo-meross-thermostat-bot-ghcr
  namespace: default
spec:
  encryptedData:
    enableOCI: AgAJH5SQZvUS8dXMfUeuzedbPgRSp14bxkJBsiD+97v7xyxy9OIB2LVtpA8CKb7Ws4EN2xYIeMLLeEtjaJv/8IdnyqlCK/vSuHRt3t+IvQImScUmYuVUJd4h7oRWSrS4EI0+YDh/N5MZtOcl8fKQg+Aq94/99obDVCJZSwckhI3Wo9uKJSYX7YL677hdvn3QV/J37hazJb3UjHKKYuQSBLLbC/mhOBtO1aKPb2WYLCQEaPKkFu6mdYNypD3MVHuQJ3X+8AGs50yaxOP4iJacR9uwdsuaouUg1kfQ23KjYGIrAVUWjm0sSKhiLWfjqF9hSSEiJxd9iYYvymwYFGRal47r0EHp1DYrKAUmRVi7bA6CxnurfVqSGBVg2aYJUhzkH1ueDPt6lzUj2FazgycPePVm9yitkBZM4UIDxhdOiYQe74YTWpJK4iTBzR5Gi3F5cUOFhFfqkUHdwaxKnTcd0dKyeMCpTK0Pj0raZ/ufotcAC0z5YZlHcsFua0l/IqzP/8l6lpc2/ujJxsZukD5ecOQP/eUucLE3OvrZ4JO5oS/z6KrlVNLp22wj2D6mOd7A3pWe1e44+CL1NC+615p65X7HDf3cKZG/YFt6LJ3RvvqpuMHnZiVvjINvFR7QERlKHcVLRO0jvySk0llL2EEt90eU6RRjsKbnzMdn2rhKQ0u8CLEdsql/58FyO2qYcamo+wFs1k9g
    name: AgCzO3PoGo/BHK2JE2togVcCO0in8/N2w9vJuj0BaD0RpaQvsWe2EnrCZNCmo/omD+Yi68Q93RlmFR3n2MAw+RzxzRzP9N0y+MasOuduqH5D1vCPRg8X82g/e+JGKNQr2Mt2e/hy2M7DBUW18nqXYLGoF5LuKp6lp4ZjfrYoPN1um7lf7D0aA9gZpiwhNcbd33bj3CC/V3np/4I4ggWVjLq8P3PffUMCk73ar+80svofh3fgqKC8gGeMH3xPujii9o+tA37uiLSQ8KA9xHdLbVvFTIq4PzST/a0F4Oz6IPj3d0Zzl0KC+fBbDEAqpMTUZg6TQJ0seGwKhzZePtbMOto3hmTppE8Gz/ghaCqE4DG6r/iUVapcwRNweLAXEOfyAXqlP49xBQ21sRYNPduI+xuuvZODbU7tobAiymxeO9NlunMG54/h/wEMlgaAWLyOL3ib2LUah9p0AWMWkHTzQgvtmguU1y5DFOOrRMeTRxUuT/vRYLrlc09jnJVsFlS6KPzO630RA2OOUYtjblx1VIh0is4a5nL3mVvhq483UL2CvVORmSEAaAqylTd2On8MnSaEHJGpa43dCY0vF2fDWGLJHZasFd0JS2uM8cLBcDjSSw7GOBKwotbWtLeVgBzueNXJMT+1MyQeqt1Od6UX+x2EshcPwkmctpEv783r0LBkjnAXSHLtLVBuy11XsF8POi+FglKhhLO+PaiZkhNh7Y39iAUC88xyfOLc3w==
    password: AgAF2EbTEqvOUh2OmeEwDcYtUKv3ND8fcbd2GY7e1akI5p/l2zHCNqHZfNNUgPnsw99fEBw5IBFVYWYS7ktiFVcvg1Z6TDcxS2oUJTXkpz35bLk66IFPtPgmJkUvcMcIBIeLorjOKEYAQeKsGmMCvEQzeG8PfZcae0j4h7AIurxL/ObdA/KS+dLhSh7VFob33DSBJAUzZxoDJ/vkrI8vv8lP+GL38oZX4HoUXohpcN84KvEQqZZ0x2Om0T9RIi8MmNtLzc/O5dbFkjLXcqru2DOdQmTXr5FuzsKfkcJ5zwZ1TTba+OZXZv2ab2y/oxS6UeGEOVzB4ktG7zG5W0mi4ON78h493yWdQlEE5qsc4nx5HtZMTaC2kaTRYybXSpJgNwnnf2AKGfe4sE/u0b8R8l2U010oZHc5WGwxxmiOqTfZONv2L0Tvrh8EY6WfKpPeltOJ7JYiOg0h7LCQks1+YPXvW1YROE6vZjkUWtYhPIXW6PvCGcZjFWc51PQXCXUV2AD7KVu1mLbie5CkjatBdqw3agwgdDQrvGeklUP04hvXFkckrZoECmQXB+i/TIN4TyclnzL+CooVWlNf/R/vdO6IhpKIIjFX/BbcsAfe7ZoKAbNt2Ub9jYt08f02Pw9eqoC8JG8+qa7ptkIiXILEP2BYm8BEozxU12XevnX7yh88CnPKNjZu2qcZYk2F61zcRNwGxCMQROWWx6BYAG71K/kQqBNzvPsjxL7XL1NvLd88j/Pw1AhTuyrz
    type: AgDTpoDBjCTKv8YoPSXFWk88JWkC6rI8n9u4oX9q1DT5DYVk2kic5nXft5NcGpC/MslA1GYdxzYHQvBMhwECdDdbKSDnPQyyHQxjctsFYmsIrw7GgO7lG59TQCTCl+c7o+VEPm299YIpBQdjg9LG7VI0bViAP3ET95USyO2d0wpJxYD3UEwyZHwzjU9e0Rhc/StbXTpztP6Q7XmH5vR4qCd9kexwxYxiJ5TueRrtiKXjmLygsdPnoz175HRa6PUDbzTtXICilr4K3UD2YGIDSR85g9Gb8ENPKmBAXSYuGmNxnmSwIYOat7F6mEnwnCFtOiQkqUX1Ne3pSGbp/3hUGMixd/AXL2H88xsAdTMNvMM6CJu0gCnszluRy8Gn9O1re7SxtwMZxpeTBbBrwb6gfwrOIFbpHo7pUsNREl9MlPE7uWfgIF5AXq5q9SZ71cL5QbGJxZOZcgkW0Xw+dcVH2y2mahB37ImRqvKdRln5gkZdfdeLQnsa29QE+n9zid2fjO7jBR4PEGiW7U97NxPmjlNRgOC2IRfstntE+5mURL1nDAFrhVr0PjvBfONAzdT08ZyNBGrdvtg16xES/ZDTiacrdQPlN9EwHFYKKA7an2HhB0xiQ39lTxy3Qc5p0ZCEHbY/uv5LN9G9zufG27Glzct4fFRC0mxsr+qEfzrYlLefXDpCJMG2GIDzs2yqG3qdnMTy1bT+
    url: AgDCp+pi7VA+buiA5mh1d7DTN05Wp+1egwD6QqV/NEViajkMGzxt+77DOqXI3AH+2kLT0rZ4SaXuOya1iMsS7F5O5yjHmm2jZZ4eENVHKy/Ob79GmBorre6vd/qNnZgpA7EgD4WcCFENs9U+sBDWvToRKlyfQmcpB5mOdeT/ScsA5gXDmjGywgwchRI826AvcyQRYNddhT+zpQR5+QyNF7+MyBkOi/VROMOcydx33b0Lih9fzDTNLA10MKEiR+aWUAT6EXaAmsbBBWyjI+MWSAs1Ls+k7M/dEL2wFWe/Hh0rFWNiBbts3fz9+T2xWmLA1z5cea6OJv/VY91qVDfQ34rtPrEyJGnj2clb0xHG0Jv5R4piQIwc/a3tv4SZqMmeTc2/NZcBcBxguKMM6/Dei368oe5Hlhg00je4yqZB2EFVVUHbwceVZ9ncH+/JefkTuOUdzJyNypBLLdmKOcCb3JVEYe2m9F8rlx4Y1Tl2K1Nce1IcQqE0JR5DaLt6UTiDsS15lDQzZPV8X82zjdEtH7gIKCktAdos1zsPfzYNHPE9iu0sRT4swvV1vHOlHTn3JDrlUsWby7kXBg7Bg+yqg0+X0rEGkVOtLE2J1EbqI1HssM8IZC8mzxHzx+KY1shIriltHYcXImwVqTveU+n6sAKEWUaLg5Uo7FCuWY+Muj5MnaCwpSnm0wnRuE6F1aYYtMA5Tk/nPst5LGk0vRLjbQ3pHP4=
    username: AgCLfEf7kWME7ztlpE8hURsEbWxNU57OheJA46nWWG1YXFC50LzOEgXbFyGe/hmMmOg0Bc3BAJjLuLdoW257K41AC1d9xC7YsvoO51GIDtb9ccUHZHIalgH0M9hpXkIgxfzbufaUjlpKnZXGKy7jTxQJQq8Z4k085hd5j8GC4hKS4vGHr/kx0KIwt+WwM7fwp2eAYFrLEEPUbXYJi3tmEX/M9RIMJ+oOvonXv1appILR8D1uaqA3oSt6jqeHjZpE/0wqgEaYJ5c+AzGptDBASVL3MSfrxIgvnvbjvgVSTT5EAiRkn9kKUNL6F0YrKD7ikYfRu/T5NWC66UCVd7zcWM/XDh4Rn0LeSL1LhF6Z5JejGsKJkK60W6K80mqPAQnUZx7vdEPM8Sv0Xyd3Vd0MT9LBBdreuDHYldbdP2/47ULcaJGYgRyD8b49YtxDmiHX/p9r8TXTWPsgdB3MMDyq5HzXH6nGmIQ0YyrFbm6LUFqf7OVCuo+NH0OQfZvGad2qEqCVpzuYKB795ihRFe73Qza0bYQUR7ltsLcycI3yJvFz7Om9S6K+Wmlqqkoh86Jt5miOCbQ6XV1xL97zn5ITT662qjzzxr5XxWiowWjEjsfupcusCuYM3rDxfpgQkl2dliVuIIrXNnWyM6ZqMVOrAxQImGvo5bV4nDs9QMvX1uyEiA++ELpEg5BXCeJvA8LRZcTwUnk=
  template:
    metadata:
      labels:
        argocd.argoproj.io/secret-type: repository
      name: repo-meross-thermostat-bot-ghcr
      namespace: default
    type: Opaque
