apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: default
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/resource-policy: keep
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  ignoreDifferences:
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
      name: bgppeers.metallb.io
      jqPathExpressions:
        - .spec.conversion.webhook.clientConfig.caBundle
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
      name: addresspools.metallb.io
      jqPathExpressions:
        - .spec.conversion.webhook.clientConfig.caBundle
  source:
    path: metallb
    repoURL: https://github.com/0Bu/rpi-k3s-cluster.git
    targetRevision: HEAD
  syncPolicy: {}
