apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}
data:
  evcc.yaml: |
    site:
      title: Zuhause
      meters:
        grid:
          - Fox ESS Smart Meter DTSU666
        pv:
          - Fox ESS H3 Smart
        battery:
          - Fox ESS EP6

    meters:
      - name: Fox ESS Smart Meter DTSU666
        type: custom
        power:
          source: modbus
          uri: 192.168.107.186:502
          id: 247
          register:
            address: 38814
            type: holding
            decode: int32
          scale: -0.1
        energy:
          source: modbus
          uri: 192.168.107.186:502
          id: 247
          register:
            address: 39617
            type: holding
            decode: uint32
          scale: 0.01
        currents:
          - source: modbus
            uri: 192.168.107.186:502
            id: 247
            register:
              address: 38816
              type: holding
              decode: int32
            scale: -0.1
          - source: modbus
            uri: 192.168.107.186:502
            id: 247
            register:
              address: 38818
              type: holding
              decode: int32
            scale: -0.1
          - source: modbus
            uri: 192.168.107.186:502
            id: 247
            register:
              address: 38820
              type: holding
              decode: int32
            scale: -0.1
        voltages:
          - source: modbus
            uri: 192.168.107.186:502
            id: 247
            register:
              address: 39123
              type: holding
              decode: int16
            scale: 0.1
          - source: modbus
            uri: 192.168.107.186:502
            id: 247
            register:
              address: 39124
              type: holding
              decode: int16
            scale: 0.1
          - source: modbus
            uri: 192.168.107.186:502
            id: 247
            register:
              address: 39125
              type: holding
              decode: int16
            scale: 0.1
        powers:
          - source: modbus
            uri: 192.168.107.186:502
            id: 247
            register:
              address: 38816
              type: holding
              decode: int32
            scale: -0.1
          - source: modbus
            uri: 192.168.107.186:502
            id: 247
            register:
              address: 38818
              type: holding
              decode: int32
            scale: -0.1
          - source: modbus
            uri: 192.168.107.186:502
            id: 247
            register:
              address: 38820
              type: holding
              decode: int32
            scale: -0.1

      - name: Fox ESS H3 Smart
        type: custom
        power:
          source: modbus
          uri: 192.168.107.186:502
          id: 247
          register:
            address: 39118
            type: holding
            decode: int32
          scale: 1
        energy:
          source: modbus
          uri: 192.168.107.186:502
          id: 247
          register:
            address: 39601
            type: holding
            decode: uint32
          scale: 0.01

      - name: Fox ESS EP6
        type: custom
        power:
          source: modbus
          uri: 192.168.107.186:502
          id: 247
          register:
            address: 39237
            type: holding
            decode: int32
          scale: 1
        energy:
          source: modbus
          uri: 192.168.107.186:502
          id: 247
          register:
            address: 39609
            type: holding
            decode: uint32
          scale: 0.01
        soc:
          source: modbus
          uri: 192.168.107.186:502
          id: 247
          register:
            address: 37612
            type: holding
            decode: uint16
          scale: 1
        capacity: 5.76
