apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-shelly-mqtt
  labels:
    app.kubernetes.io/name: telegraf
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  shelly-mqtt.conf: |-
    # Shelly Smart Devices via MQTT
    [[inputs.mqtt_consumer]]
      name_override = "shelly"
      servers = ["tcp://mosquitto:1883"]
      topics = [
        "shellypro3em-2cbcbbb2ddb8/status/#",
        "shellypro3em63-3c8a1fd182e0/status/#",
        "shellyplugsg3-8cbfea9fd6c8/status/#",
        "shellyplus1pm-a8032ab9d8e4/status/#",
        "shellypmmini-543204b695cc/status/#",
        "shelly1pmminig4-ccba97c4e854/status/#",
        "shelly1pmminig4-ccba97c65f18/status/#",
        "shellypill-d885ac1a6284/status/#",
        "shelly3em63g3-e4b063f32e48/status/#",
        "shellyplugsg3-d0cf13d87ed8/status/#",
        "shellyplugsg3-d0cf13c856a0/status/#",
        "shellyplugpmg3-907069519650/status/#"
      ]
      data_format = "json"
