apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-shelly-mqtt
  labels:
    app.kubernetes.io/name: telegraf
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  shelly-mqtt.conf: |-
    # Shelly Smart Devices via MQTT
    [[inputs.mqtt_consumer]]
      name_override = "shelly"
      servers = ["tcp://mosquitto:1883"]
      topics = ["+/status/#"]
      topic_tag = "topic"
      tagpass = { topic = ["shelly*/status", "shelly*/status/*"] }
      data_format = "json"
