apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: telegraf-influxdb-token
spec:
  template:
    metadata:
      name: telegraf-influxdb-token
  encryptedData:
    INFLUXDB_TOKEN: AgBLx6KN9bUEg6IyPgpV/E4XRb3EKUDlcVcC//oWA1RrgkTrgFRU1INUv+7P43pd7WtNo0dfhy2nxdnj/BfVJZ6H1B1dz2Y0a32iaP8sLJXF6Fe+i4YIbUHBtj3vNPgPC9ESKm0K7kFqt3YTBKM4VMEy3NnEjQaIzcRHxiHFoNWddvCFfs8GSBp2pFip46zSQQmEDX/oNwiT33nHJWcx1T0nK7nYPvBdTcuX3y31Y5TInFPiMrN2+BcXLVxg202kEDosjpH2Ri+z7CMPb3vF5l3fRHVAhqp/94o3/bsR8luxHZH2MJ4LdNKxLFMAyCYPjBEQPSHVh0yeOv0z4gYVhVCNwtgFs/wDiP3doHmzRB4ioYH2MvKyosSK4A+r121P5J1PyNBEn+gpbFlZ22bpAABwmAUq65TXSdwNdNKIxIdNb4TCfUAVdN6s2RQYU5j4ScXILVV2FcNtl8BFx+8YDhvHCDMlM+aX0eI+MpbQUzsIWncldprZ8z8KLuKdTsmWfND9hgPn05S57RfeLwHxag9E3JhzlialzanSWNvdZClPnKnQdhyG9526T7SaDCe1eF1DrX/tTpCxFlwh977ysdcm20N1Ffio/EHpUECkxVjH6e6UC7xD4uCJ4TD2Zxa7fWaTdemxR76+GDj/jwA9G2dlAtUxBI/uODWnTOy7oRBLApo7r6BninIarNquhmSE+aAZoxaqSf0Cr+bVV0Yt2o0AuyShrzhOvIMDMuAJq9/RxxzNt+yyby+FkSSO6ljhxZPznz5TStgpxny1pMKM+vEAsUxUl6RX68JwnpJW4aOkZffVWjYgg8Vy 

