apiVersion: v2
name: forgejo
description: https://forgejo.org
type: application
version: 1.0.8
# renovate: image=code.forgejo.org/forgejo/forgejo
appVersion: "16.0.4"
dependencies:
  - name: forgejo
    version: "17.1.5"
    repository: oci://code.forgejo.org/forgejo-helm
