apiVersion: v2
name: forgejo
description: https://forgejo.org
type: application
version: 1.0.4
# renovate: image=code.forgejo.org/forgejo/forgejo
appVersion: "16.0.2"
dependencies:
  - name: forgejo
    version: "17.1.4"
    repository: oci://code.forgejo.org/forgejo-helm
