{{- if not (lookup "cert-manager.io/v1" "ClusterIssuer" .Release.Namespace "selfsigned-issuer") }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "1000"
spec:
  selfSigned: {}
{{- end }}
---
{{- if not (lookup "cert-manager.io/v1" "Certificate" .Release.Namespace "selfsigned-ca") }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-ca
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "2000"
spec:
  isCA: true
  commonName: rpi-k3s-root-ca
  secretName: selfsigned-secret
  duration: 8760h # 365d
  renewBefore: 360h # 15d
  privateKey:
    algorithm: ECDSA
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
{{- end }}
---
{{- if not (lookup "cert-manager.io/v1" "ClusterIssuer" .Release.Namespace "ca-issuer") }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "3000"
spec:
  ca:
    secretName: selfsigned-secret
{{- end }}
