nfs:
  server: 192.168.1.5
  path: /nfs/grafana

grafana:
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: default-https-redirect@kubernetescrd
    hosts:
      - grafana.burau.dev
    tls:
      - hosts:
          - grafana.burau.dev
        secretName: cloudflare-tls
  persistence:
    enabled: true
    existingClaim: grafana
  plugins:
    - volkovlabs-echarts-panel
    - victoriametrics-logs-datasource
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: VictoriaLogs
          type: victoriametrics-logs-datasource
          access: proxy
          url: http://vlogs:9428
          isDefault: false
