apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: pi5b
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    repoURL: https://grafana-community.github.io/helm-charts
    chart: grafana
    targetRevision: 12.10.1
    helm:
      releaseName: grafana
      valuesObject:
        admin:
          existingSecret: grafana-admin
          userKey: admin-user
          passwordKey: admin-password
        deploymentStrategy:
          type: Recreate
        rbac:
          namespaced: true
        automountServiceAccountToken: false
        testFramework:
          enabled: false
        ingress:
          enabled: true
          ingressClassName: traefik
          hosts:
            - grafana.pi5b.burau.dev
          tls: []
        persistence:
          enabled: true
          type: pvc
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          size: 2Gi
        resources:
          requests:
            cpu: 100m
            memory: 192Mi
          limits:
            cpu: 500m
            memory: 512Mi
        grafana.ini:
          analytics:
            check_for_updates: false
            reporting_enabled: false
          server:
            domain: grafana.pi5b.burau.dev
            root_url: http://grafana.pi5b.burau.dev/
          users:
            allow_sign_up: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - ServerSideApply=true
