---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-postgresql
  namespace: default
spec:
  encryptedData:
    password: AgAg60pJLEGR3zWc6u6qCikUoEpbOY84LhPlSSrY1SPj4abiv96ckmiJQXdG+B9vn5Ms6/5e8O3JUqs2RP46Jj8ct62ohJZdB7uR+Gllf/4ExBW6YWGIARwbCxGaZDvjaGpePrNm74W73Oi9SzLaUNrMekPqWabNAftMNlQ+6NDMCUik51XUdWeW60POO79fo/AbwgPllNYk8Lo5RmUDGCwuo7y0J5EMuoBSXLYiMpsV92zQGnaQlXajtrlkoiWl7JWD0kxcFbf+AdUMexidjRDZoWed9mSUgdi6JhV2MFFaBE4zy770OJ5cg6/6cHBobpqLIk/L/jikeXVlAwynOOvjxQJwtqlT4AQKZFX87K8oWMs/LQFuLELpri5jNVtKj2jd+WTPFwnDCL5WHU2ShFqv3n5Cat8ZyunwoHnU5tJezZS0g/YZ5ncCO8NGujnZvOmEBBIMHAnrkMKQEvX8J78dZi2RpZ5glY6iJJ/VS/JvoFEbS87gwny5hwGlCm4j15kyUOtHapYE06NYmlwEsF92XU+ThE0vTspch1UHWrLxAY0cH+mLEoMvp6Vv4RtiEfbut215KPur/YLJ0VXm/KgCNKuPxv/JQp16V9eZwuWO/NUhEYLg/Yr3DzkfHjA1byLhkP/NrdmWg36qjIo9gQaFmXIRD9WP6u4evuSZ7W8Ry0DRblpjBA3rcvDRKB/oP6Xdhg+csEDlRNdKlFn1RSQhcgCsyGs08gGU1GHmQZnucg==
  template:
    metadata:
      name: forgejo-postgresql
      namespace: default
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-admin
  namespace: default
spec:
  encryptedData:
    password: AgAZiR+/fUjJ93JMs8AF5j3lIBivld0Up9E4QCe3AzxqFBKtNqBUEPp1WMhzX3W+FtLe/MPQip2qlMQ56AU7sWPrYVHk3vII0gDpThHckMFqnGXEDXPQUeuQMCY1npd6tBV2bfuD2hlvMNcKMCbVbn4i75NvBsfMRLVKw0d1+KQLl5c3H0iR+UU/JD63U9fW6ZJhRJPizZ+Dk3ocJuLdSlAg2UEW04jAtgGMI//d9XdcH4khE0uEjDkJorgS7R4zgcCgUxiQMzYdXy/tvdRw3Ah6Vd5gg4Fnk8Br0alL7uWF6LgDWmrbfPEm6RnJGCIjp6AQOCir0p6tH9pi/vmMzFMyxvKQQcbj4enWUFta4LUKhFsxDleg1rof1dAmsispCi2cXYN0FoJT3xo0TqQR+SIY9ouY//H6SfBad4xplDMkQ0ORbA3B0Uyf86+Ja983d/dJbkrwPgdVe5oamrWHbAOksVgsGyZ1a6pdeU8i6SukCnbD1OHP5YcBhJIswLVq51l1nx49477orIZwlLion81Kg7z/oW4GP+GjOzc5vnCQ3EN2RbM9UqASuXgNHLw1ZvwQa/ttuHbIQ21IvXyjxDwaJMSVoJsH6ktKZ3SYRg/18HncANeBlRhmgHgLxXgL04dtdzijv3VCBBHU1zYIG5ZlfclZftHlM+PEYH4U5oMDvWUa+HUVgreDEBo2HIPBdo8Z1WMh0N/Hmwj/ZdIDd+S3sCwkoih2A1k=
    username: AgChxrTcZOGZLxNxyCLwBvESaT0qDINMTsN2PHRK1LbWWGgr+EzcXuwngmkhcTIrPfzYlcUv8yFgozDez4nRj1/ng8uvMP7Vosw/I6NZ+ylzAWoY8mkRw7+w17Vf10ttIpYyHznZlxoKemwzxQweMuUUyT1BNyJawHYPXiDgaIQPOxHSt1lHHgfUy10wphNClnHYcke0P1TOfuZLFThroUNgdU5GIv9dBuluzvQ0gLEdvpXCtOhUuCCT6jVtSSutAl1qeOyleB7I/h7xqleg5xF+EYt02x+c1jNXTZCIgmJ5Eu730dtfpg3VUttLY7ulbd8KZu0fFbU0AuUCNf0KqiPbjv2X1oNFFHpfhhBu/ys4obnJLW54rrcLtsGgQrRitgewJFn+Fl7DLFF4cJtmvCmuBxzICo+P/earkSCXzZ+ljIr6gDR2yba437O7lZV3tZrVXKYYiAWHCqrSCseSaEMvUjzJ/4wOy6mTZ74UcvKkf0yKhwh8va+HL7EtUKFtGAeZkmR/G8nIIBcKvBFvqSViSikjmZjmPl+ib+daKgZs2wnRpGt2diVpN8ColtIAzI1dny5Khyme1PxSiYoi7aW6ZQWXnktsno18JjjbT4WIC2LZNDpGl8xkNB8WnkOj0Y0eo/Yr4bvg+GGG4Icpxa3wbUFZxyaRYUChrP8rD8rQbVBXbvRspYNd+VE7i+fTE4vRTPH/yZRExYfF0IHg
  template:
    metadata:
      name: forgejo-admin
      namespace: default
