---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-postgresql
  namespace: default
spec:
  encryptedData:
    password: AgAadONwzMtDM4l5YdCgacnV3KmwT8YdpUh/PfQamVGoPNV9yDwaIjHIlTEYyXw6IgT2S5PhUnF3iGlP5VvP6LyYTykJddBrYH8rLMbmtnbvUmqDs31/dHdQHzXC7xvUP9N11nUMJYN9Yh+N48mWSddRaqjRCjdum+1lhXyMxtUB7cqDkC18KRNeJad7JLa8JJjmAwp/q9A5DTjnsoEZOpiK751zmXMevSZC7ZbQ5J84ux6LjkjAkt3YGigLe5PDHkJyHKhpWFPrNjderzU55KUvoDEdUj1BmqcY4w+dvJkF7Ih4lKt6AFLBFE/2BgDypoyBC3UgEKJT0DTWFR0si/p5YB37W1gaTTHXjCDpUbVeD4nbRBaXTtX4uCW1dnWOUedsjf1Xa2SN87Df3ZvYZFxou/V/hh5oXXLq93uGyLzcSNPv+E7YZs+q3iCTX0IBSa0Xzcl3ZgNrHOTEfBf2Nwc8yAmIcAzcHJOLrYnCwYQSiLfTNkuBenQlkEeSAstM76lSt5zJBMIVKQqmKLROnaoctPXUqnkm9vrSMgrMj4+7vt20vxkBcbE1/0XkdoQFO/tyKMK6j1QUpYNgNS9H/8U5UAfVPAaqAxhP2BAOs+sHgyaFRh1ZO/vXmahIkET6wGzwX8JGWrYhhHLdNPq6ZW27Kaebr4go3k1qk6IQljBTfogzJCF+j5afF1RfGlsN0QjLDbKvS8/9Y5O3LB71WEuP1FMcDuompLFL5+8wCPNY0Q==
  template:
    metadata:
      name: forgejo-postgresql
      namespace: default
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-admin
  namespace: default
spec:
  encryptedData:
    password: AgDNfmOd9alyOEI/XE6sAGlz/E5MvtaKT2WAfk7XekYjAUhcWnU5cUV75UuLoFa/qbiGyTlvnUArvtpekeicBZGQ3e2QAwBMOVU587BwtkDMBSRv7m2XJ0enwfLLhCdvG/aG8p5LKv71Qsr9n4dOTbLaSf1yjFkJbvgEWf0zqsV2/y5UKg3LFvsSnjwMGNOz6pDaUV24e9enp71HdGvBnry3GuRhPaN3o7sUvWjefBz79NpmkAuP8zYfbGgFpVdNmj1Zl8xXVdPMIMqO8CnewREsNtM3BiH7tDIexm0YNK+or55YimCX6/pyHhuDJJgknQkEpIVp4hOq5K6F+CV2wxE3ie64Aorvg663gCGZIA3NuylhLoWMbL+ERRXMrMJNxWlSE4DN3tLDzrtinxhTpo02yilm1MSaGABxSmOoe5hLyZghSQcJg98mBBBCNdc6tCgHJNt/P4s+VbjkRNcKT0cYx4gV2WoC25xoEwCmXNMLY7OyZh3c3VO6MdR0jdqCf7XKny3x7B77Ps7CpltQ+hdFrOII8cc5guNpBfymFlMpbk/59V7iDO7x1rUw4KAUqIebFjLI1X+GYSsTfG7gA4NJzOD4FhZPhO3yvH/JHYZ36h8WNfOQhlLm9+URdXYONBZWr4BjJVsyR65X9V2OpdvNSoAr9/9S5UhCxvZMUE0jv0PnGwk4RKkJdgP7EX26eE5vVe/ZuNJ4sIETadv4S8GN7/Jp9SyNapQ=
    username: AgCYc/OYmgbMo1ulvE+OXH/Aw4P5S1rWydRUR0RvMsj4IqezyNmgPPcacRb84iszNOpzUU99ZbOzXLEk7cPh8PJN6VvjIA8QQ5LBFbNzCDKrXdu0qrbvv5qEb7z3VX5eVkW1jV9W/xuDSCOFAyWpTz/5dQmLqBGumsAMSww0X6fIospOJWyl7OsYWa7ZK8AGiIEuQ83qcwbhYGnHM7XsaKxO5gCYo7pYkzRVaiqkRrdRDIhdf3zO/0bX8WyKopgWjGaJPHRJbH6JigjMba+4Sp84LOcNSisAkTrzvnBK0ENQxpOvTQtzUYlUCAvlZxy1cRLMxcVUHJ7iEGi+vq9p167E36+PF12jONRWZ5l8WAMCDEAtSMb/NLdYrSaVAWqBuQJ3KB36NPt167XKv2j5zONFoCe+M/2T0+3k58PmBf6lV18yG8eqWAX6BnZxiTP04MOG7nhGe++PbwMZc61zfWFfrxXQFlJ3PFLXUA2wwyDXwwJCN9Kq0rYoV+ODqgP2iiOTmvxHJNMrjlOUUzySjV7KEMK777byll9YZFqSZ4busjS6SADu4TcnYsVRyf5EDzBDD2ii5/C113oRZBwoH++lcd3XCCvDuYSSBOmols1XpKLuoevylF3TxZjhuFvqlCbRZPTl1XJcDxkWLluxuI2ozW86bORyB5gMhalpVN7lVmrYUuWxDZy1p+qD1MCe5cnR+9Xn
  template:
    metadata:
      name: forgejo-admin
      namespace: default
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-runner
  namespace: default
spec:
  encryptedData:
    secret: AgCfIun2hkGke+TpVtcMg7rvA9xcrwjc175vv06b3W68ZFmzL4KwwDq+sSOWhf5QitqDmZlVLEXuu1AGjaNaFyLfBRgg+PvuGPw3qhIezZBMQY/iz9UOryfwdy1TrE3TJzkSdZCWLY/8Pb9m7XFElxBwjDQyZllNZXw2K2AtPB7U+gY6S5vesCoja5jDpN5mZ74x6XoKhLpCX2fJaAXaLqP1YWyAVXW6URaunjCI3kOavvrExZHZgWZwkzmR2fWXp2+GTizF/r2cIcsIkxQfh80kWpsvM88VS4wFKyxkO5RJoQy45EmhZhxyhr6Kol2CDpeV1B9KcnOwOnXp4irUBmKMLZklYyRZBaznz0LYx1rxAgNNZ9bNIW8+RmMHHOiA3WoLAtgrX4ZjAZLjvOGqWb1EoM4F4q1GjPKn79+++5lGTh/J6KyVZLseLfpPlbPwCAAnsmUFLP+1V+b1gXYNW2/kRJePbXyp4pt8YuIidmL2zoKXZmUAjIj8QRzuNSMeHHJTY9rLiNJQv0NXNc6Nxt1EoJjDcSv78p1f+5O1qldJxGR6ueI856bjI4hSA7fxQW3MGwYMEO261rd3pRlIoyb5s+uwkv5CbdMHHuV8e7iJn09qpYsdBtC9uAHb1sSqV/GxT3KRSC5MmGak2+pWRPzGg4nhC97ua0wGNj3DoqDupU8kiYrHDW9+cCY0LQ2uXtMKNJ4D6h/4bw3MUM5xvudWts7rlqEdBg3AZu40rKiGG94WzqrDQW1v
  template:
    metadata:
      name: forgejo-runner
      namespace: default
