apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb
  annotations:
    helm.sh/resource-policy: keep
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
