apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          env:
            - name: TZ
              value: "Europe/Berlin"
            - name: PGID
              value: "65534"
            - name: PUID
              value: "65534"
          readinessProbe:
            tcpSocket:
              port: 80
          livenessProbe:
            tcpSocket:
              port: 80
            failureThreshold: 30
          startupProbe:
            tcpSocket:
              port: 80
            failureThreshold: 60
          resources:
            requests:
              memory: 192M
              cpu: 250m
            limits:
              memory: 1024M
              cpu: 1.0
          volumeMounts:
            - name: homebridge
              mountPath: /homebridge
      volumes:
        - name: homebridge
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}
