apiVersion: v2
name: argocd
type: application
version: 1.0.382
# renovate: image=quay.io/argoproj/argocd
appVersion: "v3.3.0"
dependencies: 
  - name: argo-cd
    alias: argocd
    version: "9.3.7"
    repository: https://argoproj.github.io/argo-helm
