apiVersion: v2
name: argocd
type: application
version: 1.0.496
# renovate: image=quay.io/argoproj/argocd
appVersion: "v3.4.5"
dependencies: 
  - name: argo-cd
    alias: argocd
    version: "10.1.4"
    repository: https://argoproj.github.io/argo-helm
