apiVersion: v2
name: argocd
type: application
version: 1.0.485
# renovate: image=quay.io/argoproj/argocd
appVersion: "v3.4.4"
dependencies: 
  - name: argo-cd
    alias: argocd
    version: "10.0.1"
    repository: https://argoproj.github.io/argo-helm
