apiVersion: v2
name: argocd
type: application
version: 1.0.265
# renovate: image=quay.io/argoproj/argocd
appVersion: "v2.14.2"
dependencies: 
  - name: argo-cd
    alias: argocd
    version: "7.8.2"
    repository: https://argoproj.github.io/argo-helm
