apiVersion: v2
name: argocd
type: application
version: 1.0.314
# renovate: image=quay.io/argoproj/argocd
appVersion: "v3.0.9"
dependencies: 
  - name: argo-cd
    alias: argocd
    version: "8.1.2"
    repository: https://argoproj.github.io/argo-helm
