argocd:
  global:
    domain: argocd.lan
  configs:
    params:
      server.insecure: true
  server:
    service:
       annotations:
         metallb.universe.tf/address-pool: default
         metallb.universe.tf/loadBalancerIPs: 192.168.1.40
       type: LoadBalancer
    certificate:
      enabled: true
      domain: "argocd.burau.dev"
      issuer:
        group: "cert-manager.io"
        kind: "ClusterIssuer"
        name: "cloudflare-issuer"
    ingress:
      enabled: true
      hostname: "argocd.burau.dev"
      tls: true
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: default-https-redirect@kubernetescrd
