argocd:
  global:
    domain: argocd.burau.dev
  dex:
    enabled: false
  notifications:
    enabled: false
  commitServer:
    enabled: false
  configs:
    params:
      server.insecure: true
    gpg:
      keys:
        B5690EEEBB952194: |
            -----BEGIN PGP PUBLIC KEY BLOCK-----

            mQINBGWmxXYBEACyN+4viFQM6QQoKr0A2W0rGdMobTJwOZso2QPpewbyBsuL3rNW
            5OmHrWwXAhPKNqUIyOzdq8MoSxoTTuqLksoahixEL/X2nyhOBxR9GkYz/oI9R3nY
            cLRaFQoSJoVfOt61opkLUzbWAehpbgT8EKln8JsENq0+0nDlWQi0h2Q9oGmqlgVz
            skwmVZ8Leyv4Mg7hN6swyZ7moZfkkpD5+U7Z2XVurCzkSSfg4zb2lMRLJos2eCAc
            749ECsX0t7OBftF+YqgjIXixXsm2RrUqvU47OkOtZeAhvAYenbC3pr9Fha5NxoBU
            Ea+11MK9W6OcRhwvxVCUrMUR6FTSZyC//VpXTTtrRlOqpU5wGMbP3zpn9geqOXCl
            8rF7+1gAPG/o+QFQTBsVEruwi4JWogiQuQyOwAIlFe/7dvaxWZGpv/yW2+L3guL7
            xaHKFVGsayhlitQQ5Xa+P1iSgKSXDyReCbWotfqAempPySI25LHh3ScXI6NgdHSr
            SBaFojwAfgxbPTEQ6adIsKHCQofrnLrNa3UOeGDGiOOK0aYV3jiEDGAouatkNf2q
            85Eosj1f9laCqAH3YLJD7dcSne1iChK5qRTByMvIyeSD0NbNnVMFOGpXySyWtKb2
            ldpu8AWBQJsJs9FmYBcWAGBA2pp+IxaCn6rBIHIsUVFRN8OVZKsEsBkWywARAQAB
            tBtHaXRIdWIgPG5vcmVwbHlAZ2l0aHViLmNvbT6JAk4EEwEKADgWIQSWhHmhr/kn
            430aVmu1aQ7uu5UhlAUCZabFdgIbAwULCQgHAgYVCgkICwIEFgIDAQIeAQIXgAAK
            CRC1aQ7uu5UhlIMuEAClvVwC+Neoiq0AdixJZsagKHpx1QrMJWrtMRi4eXVTTaeX
            +P1unhC/AmSO4Xxd3uRoejHvfWh4F0gitUJ8XKgiejnmuGcq7Dbt5OoO1JuXGlW2
            BQ+MiGoYVw2B0sOhWDNrIBWOO/WL4LykcGnAtrRXwoS0Wx4MCydztXQY5lcnCWaW
            8rvu7WmduoOikH4HI97rqN5896dc4iBKSx8LZf+46DRCCD/5SfACplBz4hs5zen8
            TL8zd+zxjFrXbzota0jSDEGK9WGO4z55S2xScC6zv6v3Bj1OR8Bs5aodGtmamHZ7
            sE9w0RJoCfNx+9cR/rE82SrOaBpVU7urLe4lg7zaaNhqDdNV8ymuXGmIJarDgrme
            iB5bHS+dLFzLUkTgot4RFlPa9bFiJuJN6Tc9tMu5RJQ9l/zKmxDHIKWsAle5R65u
            zEq04LugTQBdEorGxfQCsF2ga9ncKTDMiAThWTvZpOP3NJ/athZRmOBpG4B9iR6r
            pRU8F/+MokG4fIMwnvtOhWQFiEzdTkJ7U5JAkPtTAmT3/mznwtPEU7DrFWSGAdqg
            IMOlxNCBeGvjwLR0qGH7cB9qHDGNoDLkjaUFpu5tPv4/ivkQaHlHJxjT0ILM6jet
            CAzKpKh48rm65tmrJX6KVpj0r2kKMscFf7s7XaPlCNCFds/YA+0puPbzJKWKfA==
            =NRlX
            -----END PGP PUBLIC KEY BLOCK-----
        88AFDEC3022870AE: |
            -----BEGIN PGP PUBLIC KEY BLOCK-----

            mDMEaBs1bxYJKwYBBAHaRw8BAQdACvkL9GdLZKRu4B+w0HFnRizjNb/fYea+hZZj
            YsPtTwO0MU9sZWcgQnVyYXUgPDQ3NTc4NTYrMEJ1QHVzZXJzLm5vcmVwbHkuZ2l0
            aHViLmNvbT6ImQQTFgoAQRYhBAzkGqhuRGgs8a9YVYiv3sMCKHCuBQJoGzVvAhsD
            BQkFo5qABQsJCAcCAiICBhUKCQgLAgQWAgMBAh4HAheAAAoJEIiv3sMCKHCuYQEB
            AOPvxUUtKpTd1ge9ZPU3meE5btDq79elir4iFV9nN3feAPwOuPiFT8iTO/YlBtG3
            BZKwi89OOp7boMhLNsKgNnMmC7g4BGgbNW8SCisGAQQBl1UBBQEBB0CvYWQqd0eM
            lDvuTN4VDctAHoq58/06VH9khEan50YuNwMBCAeIfgQYFgoAJhYhBAzkGqhuRGgs
            8a9YVYiv3sMCKHCuBQJoGzVvAhsMBQkFo5qAAAoJEIiv3sMCKHCuxgcA/jM1xDgI
            cA1JkbXnkAJXycKj0KgPxGzjteZH4wMUvkB6AP9mIK8SLB+oLwbmuqCMn1AVYGu1
            37tZxwqJgZGTiOccCQ==
            =HyMY
            -----END PGP PUBLIC KEY BLOCK-----
  server:
    service:
      annotations:
        metallb.universe.tf/address-pool: default
        metallb.universe.tf/loadBalancerIPs: 192.168.1.40
      type: LoadBalancer
    certificate:
      enabled: true
      domain: argocd.burau.dev
      issuer:
        kind: ClusterIssuer
        name: cloudflare-issuer
      annotations:
        helm.sh/resource-policy: keep
    ingress:
      enabled: true
      tls: true
