---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-postgresql
  annotations:
    helm.sh/resource-policy: keep
spec:
  storageClassName: ""
  volumeName: authentik-postgresql
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "10Gi" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-media
  annotations:
    helm.sh/resource-policy: keep
spec:
  storageClassName: ""
  volumeName: authentik-media
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "10Gi" }}
