{{- if .Values.rclone.sealedConfig }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.rclone.configSecret }}
  namespace: default
spec:
  encryptedData:
    rclone.conf: {{ .Values.rclone.sealedConfig | quote }}
  template:
    metadata:
      name: {{ .Values.rclone.configSecret }}
      namespace: default
{{- end }}
