apiVersion: v2
name: victoria-metrics
type: application
version: 1.1.1
# renovate: image=victoriametrics/victoria-metrics
appVersion: "v1.142.0"
dependencies:
  - name: victoria-metrics-k8s-stack
    alias: victoria-metrics
    version: "0.75.0"
    repository: https://victoriametrics.github.io/helm-charts/
