apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-backup
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: {{ .Values.nfs.server }}
    path: /nfs/postgresql/backup
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-backup
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: postgresql-backup
