apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: {{ .Values.nfs.server }}
    path: {{ .Values.nfs.path }}
