---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-credentials
  namespace: default
spec:
  encryptedData:
    password: AgA9UrG6CfZbpoHsq789PHFY3MYhQATJl0YghbJYddoSI08n7x664lABWVFz8o/t87L4fboAinXPhZj3BIN13fJtjlCqpOoIVs68d4zWGFupFub1avTrMpY6Qt2oTA+LEE6LbWPxsR7cip7vpd7QZjRRyRxPkssWRXyH0RYIqxZTRFgc2R0TMYrJ6ZOteqGtp1nVv/vXHQRwDHOlb64+662jLvnCvPBUUIu/SU0Qa4RFkhro42DJVIctP2wZWaX2X5xa3lBmfOaXWz1lYyZ7vbMo5SoMRAjzHHKf0Rf5Ov7UVW93xmfExXkYxn18qebJQ9ghbNvasVnfJzUbtxsstkqiL8yAuZr/KYND5x9luau85puwjIBu5DbIZNvIKrl3TkPEcw1gkHjvFOO7pGEAH/x/zKYohIyjKm8EbmxMjnyFAALpn64Jk5R5yvRmG+ohPsUDjc4SlmdgpVq+wDHH8XK3bDtyd4mN2tWYcpS9xmfqvgY2lppG3rukWmGAhHebemAKHk1W8mwzYqpaMCdP2oJYREBWOGK/eRyjq6MV8vbWz6krOpOOwB8htbnhdd4Yqm9SqlTXA9mqKGeJNKnzN/JraGExpxlBXjdjKrczpyXVMrMNIQOuieVpN+S/+Znm6+Os25Du8FOd33PR5k/0MZU1FsrBmBbhm0pu/L/kUQSGVeGhjntkMX0cUnj0M1JKUF0GLzhfORpK4NK2KoJoJ/+dyM1tcGGXGZOiTQkPEA4FuA==
    postgres-password: AgAQ0aGLq41b0/rIn/JqN61sdm/sndXi34pzZtziz16BzbmPWSCrq9rCwwSvC6dBOEflKLEEtN8KgT35bM+KG9ScUkuzHd7tFpkZMkmeeAq2PRPGh5I2RD/cT5rMx7Fki/Zmf4Pmaa7+zxneOwoK2WeHpRdU4PW4UJPR2YyYpQnNeI/HqEZl7mEVyilj2wYsSJhuIR2n/C8AryBx4Vw/D7I5xEbyn4dE2E5LYSLE2nttV5gKlF+dMcqDmdhr31+6BnyWLCY21lDD8IDOPCzwjz6r68qff9Yo5WNp0M1R/ioX0dHfjFdBEv+rsd48aU/FSqDpKKjdkDM9mq7gprG8fwIBzCnc52gKWvE+xfmdXKMg2oSRMSUmP3jsiPlbblhJDEID2XGzs03pMvttM6BtSW0Aucjb2v/F3tV/QTkY8L1boNfrGO+uikc5CxphxgJ8KitxY2I/Y2GUYFkjqRaG5hA+YQnrT/fijCj/4b884NsiC0u5IzkUBLS9j1NMlfQaQmObzbIMkE6/baRpdIGMvdzLlUkgYddepqsqnGHh4MMU3djYCMrR/Kf6W0HCYVhO6bxEELHjSiEVzNdLXNy2vlWchDs/+NzQTnRGgj30EKgOR/YzpZbnVamdSTfGSlcqF2U/bt4M2IhDDV1/prZc4kaU+2tNgKkMcL/0fayrUm70p793ThqqzFmAOi9yk6f9cWWdXtJmVL7vYPneLXtMADBAF4jf46tObChltk+Jin3i
  template:
    metadata:
      name: postgresql-credentials
      namespace: default
