apiVersion: apps/v1
kind: Deployment
metadata:
  name: deconz-{{ required "Required host, e.g. --set host=pi4a" .Values.host }}
  labels:
    app: deconz-{{ .Values.host }}
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: deconz-{{ .Values.host }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: deconz-{{ .Values.host }}
    spec:
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.host }}
      containers:
      - name: deconz
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        securityContext:
          privileged: true
        env:
          - name: DECONZ_BAUDRATE
            value: "115200"
          - name: DECONZ_WEB_PORT
            value: "80"
          - name: DECONZ_WS_PORT 
            value: "443"
          - name: DECONZ_DEVICE
            value: {{ .Values.device | default  "/dev/ttyACM0" }}
          - name: TZ
            value: "Europe/Berlin"
          - name: DECONZ_UPNP
            value: "0"
          - name: DECONZ_VNC_MODE
            value: {{ default "1" .Values.vncMode | quote }}
          - name: DECONZ_VNC_PORT
            value: "5900"
          - name: DECONZ_VNC_PASSWORD
            value: {{ default "deconz" .Values.vncPassword | quote }}
        readinessProbe:
          tcpSocket:
            port: 80
        livenessProbe:
          tcpSocket:
            port: 80
        startupProbe:
          tcpSocket:
            port: 80
          failureThreshold: 18
        resources:
          requests:
            memory: 128M
          limits:
            memory: 384M
        volumeMounts:
          - name: conbee
            mountPath: {{ .Values.device | default  "/dev/ttyACM0" }}
          - name: deconz
            mountPath: /opt/deCONZ
            subPath: {{ .Values.host }}
      volumes:
        - name: conbee
          hostPath:
            path: {{ .Values.device | default  "/dev/ttyACM0" }}
        - name: deconz
          persistentVolumeClaim:
            claimName: deconz-{{ .Values.host }}

