apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deconz-{{ required "Required host, e.g. --set host=pi4a" .Values.host }}
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-issuer
    cert-manager.io/private-key-algorithm: ECDSA
    cert-manager.io/private-key-rotation-policy: Always
    traefik.ingress.kubernetes.io/router.middlewares: default-https-redirect@kubernetescrd
spec:
  rules:
    - host: deconz-{{ .Values.host }}.burau.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: deconz-{{ .Values.host }}
                port:
                  name: http
  tls:
    - hosts:
        - deconz-{{ .Values.host }}.burau.dev
      secretName: deconz-{{ .Values.host }}-ingress-tls
