apiVersion: v1
kind: PersistentVolume
metadata:
  name: deconz-{{ required "Required host, e.g. --set host=pi4a" .Values.host }}
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.nfs.server }}
    path: {{ .Values.nfs.path }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deconz-{{ required "Required host e.g. --set host=pi4a" .Values.host }}
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
