apiVersion: v2
name: homebridge 
description: https://github.com/homebridge/homebridge
type: application
version: 1.0.0
# renovate: datasource=docker depName=homebridge/homebridge versioning=loose
appVersion: "2025-05-14"
