apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}
spec:
  storageClassName: ""
  volumeName: adguard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
