apiVersion: v2
name: telegraf
type: application
version: 1.0.44
# renovate: image=telegraf
appVersion: "1.37.3"
dependencies: 
  - name: telegraf
    version: "1.8.67"
    repository: https://helm.influxdata.com
