apiVersion: v2
name: telegraf
type: application
version: 1.0.33
# renovate: image=telegraf
appVersion: "1.35.0"
dependencies: 
  - name: telegraf
    version: "1.8.58"
    repository: https://helm.influxdata.com
