apiVersion: v2
name: telegraf
type: application
version: 1.0.57
# renovate: image=telegraf
appVersion: "1.38.4"
dependencies: 
  - name: telegraf
    version: "1.8.70"
    repository: https://helm.influxdata.com
