apiVersion: v2
name: telegraf
type: application
version: 1.0.51
# renovate: image=telegraf
appVersion: "1.38.2"
dependencies: 
  - name: telegraf
    version: "1.8.69"
    repository: https://helm.influxdata.com
