apiVersion: v2
name: telegraf
type: application
version: 1.0.37
# renovate: image=telegraf
appVersion: "1.36.1"
dependencies: 
  - name: telegraf
    version: "1.8.62"
    repository: https://helm.influxdata.com
