apiVersion: v2
name: telegraf
type: application
version: 1.0.39
# renovate: image=telegraf
appVersion: "1.36.3"
dependencies: 
  - name: telegraf
    version: "1.8.64"
    repository: https://helm.influxdata.com
