apiVersion: v2
name: telegraf
type: application
version: 1.0.30
# renovate: image=telegraf
appVersion: "1.34.0"
dependencies: 
  - name: telegraf
    version: "1.8.55"
    repository: https://helm.influxdata.com
