telegraf:
  service:
    enabled: false
  pdb:
    create: false
  envFromSecret: telegraf-influxdb-token
  env:
    - name: INFLUXDB_URL
      value: "http://influxdb"
  config: # https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md
    agent:
      interval: "10s"
      round_interval: true
      metric_batch_size: 1000
      metric_buffer_limit: 10000
      collection_jitter: "0s"
      flush_interval: "10s"
      flush_jitter: "0s"
      precision: ""
      debug: false
      quiet: false
      logfile: ""
      hostname: "$HOSTNAME"
      omit_hostname: true
    outputs:
      - influxdb_v2:
          urls:
            - "${INFLUXDB_URL}"
          token: "${INFLUXDB_TOKEN}"
          organization: "influxdata"
          bucket: "power"
          namepass: ["shelly"]
      - influxdb_v2:
          urls:
            - "${INFLUXDB_URL}"
          token: "${INFLUXDB_TOKEN}"
          organization: "influxdata"
          bucket: "ems-esp"
          namepass: ["ems-esp"]
      - file:
          files: ["stdout"]
          namepass: ["shelly"]
    inputs:
      - mqtt_consumer: # https://emsesp.org
          name_override: "ems-esp"
          servers: ["tcp://mosquitto:1883"]
          topics: 
            - "ems-esp/#"
          data_format: "json"
      - mqtt_consumer:
          name_override: "shelly"
          servers: ["tcp://mosquitto:1883"]
          topics:
            - "shellypro3em-2cbcbbb2ddb8/status/#"
            - "shellyplugsg3-8cbfea9fd6c8/status/#"
            - "shellyplus1pm-a8032ab9d8e4/status/#"
            - "shellypmmini-543204b695cc/status/#"
            - "shelly1pmminig4-ccba97c4e854/status/#"
            - "shelly1pmminig4-ccba97c65f18/status/#"
          data_format: "json"

