apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-issuer
    cert-manager.io/private-key-algorithm: ECDSA
    cert-manager.io/private-key-rotation-policy: Always
    traefik.ingress.kubernetes.io/router.middlewares: default-https-redirect@kubernetescrd
spec:
  rules:
    - host: {{ .Release.Name }}.burau.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-http
                port:
                  name: http
  tls:
    - hosts:
        - {{ .Release.Name }}.burau.dev
      secretName: {{ .Release.Name }}-ingress-tls
