apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-http
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: http
    protocol: TCP
    port: 8080
