apiVersion: v2
name: cert-manager
type: application
version: 1.0.9
# renovate: image=bitnami/cert-manager
appVersion: "1.17.0"
dependencies: 
  - name: cert-manager
    version: "v1.17.0"
    repository: https://charts.jetstack.io
