apiVersion: v2
name: cert-manager
type: application
version: 1.0.7
# renovate: image=bitnami/cert-manager
appVersion: "1.16.2"
dependencies: 
  - name: cert-manager
    version: "v1.16.2"
    repository: https://charts.jetstack.io
