apiVersion: v2
name: cert-manager
type: application
version: 1.0.12
# renovate: image=bitnami/cert-manager
appVersion: "1.17.2"
dependencies: 
  - name: cert-manager
    version: "v1.18.0"
    repository: https://charts.jetstack.io
